- name: Get JSON from PhpStorm URL
  uri:
    url: "{{ phpstorm_releases_url }}"
    method: GET
    return_content: yes
  register: phpstorm_releases
  tags: phpstorm

- name: Get latest version number and download url
  set_fact:
    phpstorm_available_version: "{{ phpstorm_releases.json.PS[0].version }}"
    phpstorm_available_url: "{{ phpstorm_releases.json.PS[0].downloads.linux.link }}"
    phpstorm_available_build: "{{ phpstorm_releases.json.PS[0].build }}"
  when:
    - phpstorm_releases.json.PS[0].version is defined
    - phpstorm_releases.json.PS[0].downloads.linux.link is defined
    - phpstorm_releases.json.PS[0].build is defined
  tags: phpstorm

- name: Is phpstorm installed?
  stat:
    path: "{{ phpstorm_install_path }}/build.txt"
  register: phpstorm_installed
  tags: phpstorm

- name: Get local phpstorm build version
  slurp:
    src: "{{ phpstorm_install_path }}/build.txt"
  register: phpstorm_local_build_version
  when: phpstorm_installed.stat.exists
  tags: phpstorm

- name: Compare phpstorm version local vs remote
  set_fact:
    install_new_phpstorm: true
  when:
    - phpstorm_installed.stat.exists
    - phpstorm_local_build_version['content'] | b64decode | trim != "PS-"+phpstorm_available_build
  tags: phpstorm

- name: Download latest version of PhpStorm
  get_url:
    url: "{{ phpstorm_available_url }}"
    dest: "/tmp/PhpStorm-{{ phpstorm_available_version }}.tar.gz"
  tags: phpstorm
  when: install_new_phpstorm is defined or not phpstorm_installed.stat.exists

- name: Create PhpStorm install directory
  become: true
  file:
    path: "{{ phpstorm_install_path }}"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
  tags: phpstorm
  when: not phpstorm_installed.stat.exists

- name: Extract PhpStorm
  unarchive:
    extra_opts: ['--strip-components=1']
    src: "/tmp/PhpStorm-{{ phpstorm_available_version }}.tar.gz"
    remote_src: 'yes'
    dest: "{{ phpstorm_install_path }}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
  tags: phpstorm
  when: install_new_phpstorm is defined or not phpstorm_installed.stat.exists

- name: Check if libvirt firewall zone exists
  command: firewall-cmd --get-zones
  become: true
  register: libvirt_firewall
  tags: phpstorm

- name: Enable xdebug port on libvirt firewall zone
  ansible.posix.firewalld:
    zone: libvirt
    port: 9003/tcp
    permanent: yes
    state: enabled
  when: libvirt_firewall.stdout is search("libvirt")
  register: opened_port
  become: true
  tags: phpstorm

- name: Restart firewalld if port has been opened
  ansible.builtin.systemd:
    state: restarted
    name: firewalld
  when: opened_port.changed
  become: true
  tags: phpstorm

